data<-read.table("D:\\CourseraCourses\\ExploratoryDataAnalysis\\household_power_consumption.txt", sep=";", header=T, stringsAsFactors=F)
data$Date<-as.Date(data$Date, "%d/%m/%y%y")
data<-subset(data,Date>=as.Date("2007-02-01") & Date<=as.Date("2007-02-02"))
data$timestamp<-strptime(paste(data[,1],data[,2]), "%Y-%m-%d %H:%M:%S")
png("D:\\CourseraCourses\\ExploratoryDataAnalysis\\plot3.png", width = 480, height = 480)
plot(data[,7]~as.POSIXct(data[,10]),type="l", xlab="",ylab="Energy sub Metering")
lines(data[,8]~as.POSIXct(data[,10]),type="l",col="red")
lines(data[,9]~as.POSIXct(data[,10]),type="l",col="blue")
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
